# Generated by Django 3.2.7 on 2021-11-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='writer',
        ),
    ]
