# Generated by Django 3.2.7 on 2021-11-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20211102_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['user']},
        ),
    ]
