# Generated by Django 3.2.7 on 2021-11-05 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20211103_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterOrderWithRespectTo(
            name='todolist',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='createTodo',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='text',
        ),
    ]
