# Generated by Django 3.2.8 on 2021-11-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20211104_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='timestamp',
        ),
    ]
