# Generated by Django 3.2.8 on 2021-11-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_notemodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
