# Generated by Django 3.2.8 on 2021-11-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_notemodel_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='user',
        ),
    ]
