# Generated by Django 3.2.8 on 2021-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_remove_notemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
