# Generated by Django 3.2.8 on 2021-11-05 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_alter_notemodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
