# Generated by Django 3.2.8 on 2021-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=300)),
                ('lecturer', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
