# Generated by Django 3.2.8 on 2021-10-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20211026_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='color',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='link',
        ),
    ]
