# Generated by Django 3.2.8 on 2021-10-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20211027_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='year',
            field=models.IntegerField(),
        ),
    ]
