# Generated by Django 3.2.8 on 2021-10-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20211028_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
