# Generated by Django 3.2.8 on 2021-10-25 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_following_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 25, 5, 29, 15, 639916, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
