# Generated by Django 3.2.8 on 2021-10-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymsg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymousmessage',
            old_name='msg_answer',
            new_name='anonymous_answer',
        ),
        migrations.RenameField(
            model_name='anonymousmessage',
            old_name='msg_question',
            new_name='anonymous_question',
        ),
    ]
