# Generated by Django 3.2.8 on 2021-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymsg', '0003_alter_anonymousmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousmessage',
            name='anonymous_answer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
